name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:

  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 7.4.0
          - 7.3.0

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build Xyce
      run: >-
        docker run --rm
        -v $(pwd):/src/
        -e XYCE_VERSION='${{ matrix.version }}'
        ghcr.io/hdl/debian/bullseye/build/build
        /src/.github/build.sh

    - uses: actions/upload-artifact@v3
      with:
        name: Xyce-${{ matrix.version }}
        path: build/dist
